### PR TITLE
Upstream LineageOS

### PR DESCRIPTION
**Pull request by khusika**

### CODE REVIEW

**Review by justks — APPROVED** [review]

**Comment by khusika** [comment]
Ping @mohancm :p

**Comment by justks** [comment]
Lol, he can't even maintain this device properly.
Clearly he is ignoring you, don't waste your time here xD

**Comment by mohancm** [comment]
@kubersharma001 and you don't know what those changes impact 🤣🤣🤣

**Comment by kubersharma001** [comment]
Stop commenting like a turd. 
That's gonna take ya down, no replies needed.

**Comment by kubersharma001** [comment]
Also, read my first comment!! 
Think, understand and then only reply - also it's better you don't.

**Comment by justks** [comment]
Nice job deleting stuff.

**Comment by mohancm** [comment]
Okay cry!

**Pull request closed without merging**
